#!/bin/bash

export BENCH_ROOT=$( cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )
. ${BENCH_ROOT}/../../../../scripts/environment.sh

[ ! -d "./logs" ] && logfatal "You must create './logs' directory before running this script."

rank=$1
if [ "${rank}" == "0" ]; then
    python $experimenter run --config=./config.json -Pmxnet.rank=$rank -Pmxnet.scheduler=true
else
    python $experimenter run --config=./config.json -Pmxnet.rank=$rank
fi
