#!/bin/bash

export BENCH_ROOT=$( cd $( dirname "${BASH_SOURCE[0]}" ) && pwd )
. ${BENCH_ROOT}/../../../scripts/environment.sh

[[ -d "./reports" ]] && rm -rf ./reports
mkdir ./reports

phase=inference

python $logparser ./logs/${phase} --recursive --ignore_errors --output_file ./reports/${phase}.json
python $reporter --summary_file ./reports/${phase}.json --type='exploration' --target_variable='results.time' > ./reports/${phase}.txt

exit 0
